### ISSUE TITLE
AppVeyor build failing after removing .nuget folder

### ISSUE THREAD

**Issue by ivaylokenov** [TelerikAcademy/ShowcaseSystem#120]
Possible solution: http://help.appveyor.com/discussions/problems/1237-reference-not-found-with-nuget-auto-restore

**Comment by NikolayIT** [comment]
Fixed with https://github.com/TelerikAcademy/ShowcaseSystem/commit/5f5ef4eabea7849b980892b5d71d4fda821bf960 and https://github.com/TelerikAcademy/ShowcaseSystem/commit/0f44791e250bfed97954f3bcc5ac39b5735d97f0
